# -*- coding: utf-8 -*-
"""CrewAI_blogs

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gQfAgnTs0MdMEQkkLKCuI62G_i3Sl4VN
"""

pip install  crewai  crewai_tools crewai langchain langchain_google-genai -q

from crewai import Agent, Task, Crew, Process
import sys

import getpass
import os

if "GOOGLE_API_KEY" not in os.environ:
    os.environ["GOOGLE_API_KEY"] = getpass.getpass("Provide your Google API Key")

from langchain_google_genai import ChatGoogleGenerativeAI

llm = ChatGoogleGenerativeAI(model="gemini-pro")

def get_blog_topic():
    return input("Enter the topic you want for the blog: ")

blog_topic = get_blog_topic()

researcher = Agent(
    role="Research",
    goal=f"Research on {blog_topic}",
    backstory=f"You are an AI which is interested in understanding {blog_topic}.",
    verbose=True,
    allow_delegation=False,
    llm=llm)

writer = Agent(
    role="writer",
    goal=f"To write a funny but informative blog post on {blog_topic}",
    backstory=f"You are an AI Assistant who is really good at writing blogs that are both funny and informative at the same time.",
    verbose=True,
    allow_delegation=False,
    llm=llm
)

task1 = Task(
    description=f"Investigate {blog_topic}",
    agent=researcher,
    expected_output=f"Detailed research on {blog_topic}."
)
task2 = Task(
    description=f"Write an interesting blog post about {blog_topic}",
    agent=writer,
    expected_output=f"Engaging blog post explaining {blog_topic} in a simple and relatable way."
)

crew = Crew(
    agents=[researcher, writer],
    tasks=[task1, task2],
    verbose=2,
    process=Process.sequential
)

result = crew.kickoff()

print(result)